#!/usr/bin/env python3
"""Generate the production body-region table from the archived artwork definition."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'doc/VTune_BodyMap/res/VTune/body-map/definition.json'
OUTPUT = ROOT / 'src/vtune/BodyMapData.hpp'


def cpp_float(value):
    text = format(float(value), '.9g')
    if '.' not in text and 'e' not in text:
        text += '.'
    return text + 'f'


def generate():
    data = json.loads(SOURCE.read_text(encoding='utf-8'))
    lines = [
        '// Generated by tools/vtune/generate_body_map_data.py.',
        '// Source: doc/VTune_BodyMap/res/VTune/body-map/definition.json (body bands only).',
        '#pragma once', '#include <array>', '#include <cstddef>',
        'namespace vtune_body {',
        f'constexpr std::size_t kBandCount = {len(data["bands"])};',
        'struct BandDefinition { float lowHz, highHz; const char* label; const char* asset; };',
    ]
    for name, value in (
        ('kSourceWidth', data['source_width']), ('kSourceHeight', data['source_height']),
        ('kMinHz', data['report_range_hz'][0]), ('kMaxHz', data['report_range_hz'][1]),
        ('kBoundaryHalfWidthOctaves', data['boundary_half_width_octaves']),
        ('kSmoothingSeconds', data['ui_smoothing_seconds']), ('kDefaultOpacity', data['opacity_default']),
    ):
        lines.append(f'constexpr float {name} = {cpp_float(value)};')
    lines.append('static constexpr std::array<BandDefinition, kBandCount> kBands = {{')
    for i, band in enumerate(data['bands']):
        label = json.dumps(band['label'], ensure_ascii=False)
        lines.append(f'    {{{cpp_float(band["low_hz"])}, {cpp_float(band["high_hz"])}, '
                     f'{label}, "res/VTune/body-map/band_{i}.png"}},')
    lines.extend(['}};', '} // namespace vtune_body', ''])
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generate()
    if args.check:
        if OUTPUT.read_text(encoding='utf-8') != result:
            raise SystemExit('BodyMapData.hpp is stale; run tools/vtune/generate_body_map_data.py')
        print('V.Tune body-map data: PASS')
    else:
        OUTPUT.write_text(result, encoding='utf-8')
