#!/usr/bin/env python3
"""Generate deterministic C++11 descriptors from the reviewed experimental seeds."""
import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / 'doc/Vessel/vessel_seed_profiles.json'
OUTPUT = ROOT / 'src/vessel/SeedProfiles.hpp'


def number(value, positive=False, nonnegative=False):
    value = float(value)
    if not math.isfinite(value) or (positive and value <= 0) or (nonnegative and value < 0):
        raise ValueError(f'invalid coefficient: {value}')
    return format(value, '.17g')


def generate():
    # Git/MSYS2 may check out CRLF on Windows. Provenance must not depend on
    # the checkout's newline convention.
    raw = SOURCE.read_bytes().replace(b'\r\n', b'\n')
    data = json.loads(raw)
    if data['schemaVersion'] != 1:
        raise ValueError('unsupported seed schema')
    lines = ['#pragma once', '', '// Generated by tools/vessel/generate_profiles.py; edit the JSON source.',
             '// Only published metal frequencies are measured. All other seeds are provisional.',
             f'// Source SHA-256: {hashlib.sha256(raw).hexdigest()}',
             '#include "Types.hpp"', '', 'namespace vessel {', '',
             'static const BowlDescriptor seedBowls[] = {']
    ids = set()
    for bowl in data['bowls']:
        ident = bowl['stableId']
        if ident in ids or not 1 <= len(bowl['pairs']) <= 12 or bowl['descriptorVersion'] < 1:
            raise ValueError('invalid/duplicate bowl descriptor')
        ids.add(ident)
        lines.append('    {' + json.dumps(ident) + ', ' + str(bowl['descriptorVersion']) + ', '
                     + number(bowl['effectiveRimRadiusMeters'], positive=True) + ', '
                     + str(len(bowl['pairs'])) + ', {{')
        previous_order = 1
        for pair in bowl['pairs']:
            order = pair['azimuthalOrder']
            if not isinstance(order, int) or order <= previous_order:
                raise ValueError('orders must be distinct, increasing integers >= 2')
            previous_order = order
            values = [str(order), number(pair['centerRatio'], positive=True),
                      number(pair['splitCents'], nonnegative=True), number(pair['orientationRadians'])]
            values += [number(pair[k], positive=True) for k in
                       ['massAKg', 'massBKg', 't60ASeconds', 't60BSeconds']]
            values += [number(pair[k], nonnegative=True) for k in ['radiationA', 'radiationB']]
            lines.append('        {' + ', '.join(values) + '},')
        lines.append('    }}},')
    lines += ['};', '', 'static const MalletDescriptor seedMallets[] = {']
    for mallet in data['mallets']:
        if mallet['stableId'] in ids or mallet['contactExponent'] != 1.5:
            raise ValueError('duplicate ID or unsupported impact exponent (initial engine requires 1.5)')
        ids.add(mallet['stableId'])
        if not 0 <= mallet['muK'] <= mallet['muS'] or not 0 <= mallet['fullAngularPatchWidthRadians'] <= 2*math.pi:
            raise ValueError('invalid friction or patch coefficients')
        values = [json.dumps(mallet['stableId'])]
        values += [number(mallet[k], positive=True) for k in
                   ['massKg', 'contactStiffnessNPerMeterPowerP', 'contactExponent']]
        values += [number(mallet[k], nonnegative=True) for k in
                   ['loadingDampingNsPerMeter', 'fullAngularPatchWidthRadians', 'muS', 'muK']]
        values += [number(mallet[k], positive=True) for k in
                   ['weakeningVelocityMetersPerSecond', 'regularizationVelocityMetersPerSecond']]
        lines.append('    {' + ', '.join(values) + '},')
    lines += ['};', '', 'constexpr std::size_t seedBowlCount = sizeof(seedBowls) / sizeof(seedBowls[0]);',
              'constexpr std::size_t seedMalletCount = sizeof(seedMallets) / sizeof(seedMallets[0]);',
              '', '} // namespace vessel', '']
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != text:
            raise SystemExit('Vessel profiles are stale; run tools/vessel/generate_profiles.py')
        print('Vessel profile generation: PASS')
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(text, encoding='utf-8')
        print(OUTPUT)
