#!/usr/bin/env python3
"""Generate monotone cubic friction-function tables and their slope bound."""
import argparse
from decimal import Decimal, localcontext
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT/'tools/vessel/experiments/FrictionTables.hpp'
RUNTIME_TARGET = ROOT/'src/vessel/FrictionTanhTable.hpp'

def table(count, maximum, value, slope):
    h = maximum/count
    result = []
    for i in range(count):
        a, z = value(i*h), value((i+1)*h)
        delta = z-a
        b, e = h*slope(i*h), h*slope((i+1)*h)
        # Limit normalized endpoint slopes to the monotone Hermite rectangle.
        # This also makes exactly flat, rounded tanh intervals constant.
        lo, hi = min(0.,3*delta), max(0.,3*delta)
        b, e = min(hi,max(lo,b)), min(hi,max(lo,e))
        c, d = 3*delta-2*b-e, b+e-2*delta
        result.append((a,b,c,d))
    return result

def slope_bounds(rows, inv_h):
    low, high = 0., 0.
    for _,b,c,d in rows:
        points = [0.,1.]
        if d and 0 < -c/(3*d) < 1:
            points.append(-c/(3*d))
        values = [(b+t*(2*c+3*d*t))*inv_h for t in points]
        low, high = min(low,*values), max(high,*values)
    return low, high

def gaussian(x):
    with localcontext() as context:
        context.prec = 80
        a = Decimal(x)
        return float((-a*a).exp())

def tanh(x):
    with localcontext() as context:
        context.prec = 80
        e = (2*Decimal(x)).exp()
        return float((e-1)/(e+1))

def generate():
    g = table(1024,8.,gaussian,lambda x: -2*x*gaussian(x))
    t = table(2048,20.,tanh,lambda x: 1-tanh(x)**2)
    minimum,_ = slope_bounds(g,128.)
    lower,_ = slope_bounds(t,102.4)
    if lower < -1e-12:
        raise RuntimeError('tanh table lost monotonicity')
    # Bound the exact quadratic derivative in every interval, with roundoff margin.
    bound = -minimum*(1+1e-8)+1e-12
    lines = ['#pragma once', '', '// Generated by tools/vessel/generate_friction_tables.py; do not edit.',
             '// Monotone Hermite curves, with derivatives from the same cubic.',
             'namespace vessel { namespace friction_tables {',
             f'constexpr double gaussianNegativeSlopeBound = {bound:.17g};',
             f'constexpr double tanhNegativeSlopeBound = {max(0.,-lower)+1e-14:.17g};']
    for name,rows in [('gaussian',g),('tanhCurve',t)]:
        lines.append(f'static constexpr double {name}[{len(rows)}][4] = {{')
        lines.extend('    {'+', '.join(format(x,'.17g') for x in row)+'},' for row in rows)
        lines.append('};')
    lines.extend(['} } // namespace vessel::friction_tables',''])
    return '\n'.join(lines)

if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    content=generate()
    # Runtime needs only tanh; keep Gaussian lookup experimental.
    constants = [line for line in content.splitlines() if line.startswith('constexpr double')]
    table_start = content.index('static constexpr double tanhCurve')
    table_end = content.index('};',table_start)+2
    runtime = '\n'.join(['#pragma once',
        '// Generated by tools/vessel/generate_friction_tables.py; do not edit.',
        '// Conservative Gaussian bound retained to match the validated combined candidate.',
        'namespace vessel { namespace friction_tanh {', *constants,
        content[table_start:table_end], '} } // namespace vessel::friction_tanh',''])
    for path, expected in [(TARGET,content),(RUNTIME_TARGET,runtime)]:
        if args.check:
            if not path.exists() or path.read_text()!=expected:
                raise SystemExit(str(path)+' is stale')
        else:
            path.write_text(expected)
