#!/usr/bin/env python3
"""Bake deterministic aligned RGBA textures and C++ tables; no image generator.

Requires Python 3.10+, numpy, Pillow, scipy. These are build-time tools only.
Black source pixels are background. The source image is not altered in place.
"""
from __future__ import annotations
import argparse
import json
import hashlib
from pathlib import Path
import numpy as np
from PIL import Image
from scipy import ndimage as ndi

ROOT=Path(__file__).resolve().parents[1]

def cpp_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)

def write_header(data: dict, out: Path) -> None:
    bands=data['bands']; tones=data['tones']
    text='''// Generated by tools/build_assets.py. Edit definition.json, not this file.
#pragma once
#include <array>
#include <cstddef>
namespace vtune_body {
constexpr std::size_t kBandCount = 7;
constexpr std::size_t kToneCount = 7;
constexpr std::size_t kLayerCount = kBandCount + kToneCount;
struct BandDefinition { float lowHz, highHz; const char* label; const char* asset; };
struct ToneDefinition { float frequencyHz; const char* label; const char* asset; };
'''
    for name,value in [('kSourceWidth',data['source_width']),('kSourceHeight',data['source_height']),
                       ('kMinHz',data['report_range_hz'][0]),('kMaxHz',data['report_range_hz'][1]),
                       ('kBoundaryHalfWidthOctaves',data['boundary_half_width_octaves']),
                       ('kToneSupportCents',data['tone_support_cents']),
                       ('kSmoothingSeconds',data['ui_smoothing_seconds']),
                       ('kDefaultOpacity',data['opacity_default']),
                       ('kCombinedReportGain',data['combined_report_gain']),
                       ('kCombinedSymbolicGain',data['combined_symbolic_gain'])]:
        text+=f'constexpr float {name} = {float(value):.9g}f;\n'.replace(' = 788f;', ' = 788.f;').replace(' = 1002f;', ' = 1002.f;')
    # C++ requires a decimal point/exponent before a float suffix.
    import re
    text=re.sub(r'= (\d+)f;',r'= \1.f;',text)
    text+='static constexpr std::array<BandDefinition, kBandCount> kBands = {{\n'
    for i,b in enumerate(bands):
        text+=f'    {{{b["low_hz"]}.f, {b["high_hz"]}.f, {cpp_string(b["label"])}, "res/VTune/body-map/band_{i}.png"}},\n'
    text+='}};\nstatic constexpr std::array<ToneDefinition, kToneCount> kTones = {{\n'
    for i,t in enumerate(tones):
        text+=f'    {{{t["frequency_hz"]}.f, {cpp_string(str(t["frequency_hz"])+" Hz · "+t["label"])}, "res/VTune/body-map/tone_{i}.png"}},\n'
    text+='}};\n} // namespace vtune_body\n'
    out.write_text(text)

def main() -> None:
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--source',type=Path,default=ROOT/'reference/VFOutline.png')
    args=ap.parse_args()
    dst=ROOT/'res/VTune/body-map'
    data=json.loads((dst/'definition.json').read_text())
    src=Image.open(args.source).convert('RGBA')
    w,h=src.size
    if (w,h)!=(data['source_width'],data['source_height']):
        raise SystemExit('Source dimensions changed: re-register the definition before baking.')
    rgba=np.array(src)
    # Analysis of this input: its alpha is fully opaque, and it has a black matte.
    rgb=rgba[:,:,:3].astype(np.float32)
    wall=(rgb.max(axis=2)>0)&(rgba[:,:,3]>0)
    labels,_=ndi.label(~wall)
    outside=np.unique(np.concatenate([labels[0],labels[-1],labels[:,0],labels[:,-1]]))
    outside=outside[outside!=0]
    body=~np.isin(labels,outside)
    for x,y in data['holes_seed_xy']:
        hole=labels[y,x]
        if hole==0 or hole in outside:
            raise SystemExit('A negative-space seed no longer lands inside an enclosed black hole.')
        body[labels==hole]=False
    # Fade inward only. Unlike blurring a silhouette, this cannot leak through
    # the underarm holes or beyond the body into the surrounding panel.
    distance=ndi.distance_transform_edt(body)
    t=np.clip((distance-.5)/5.0,0,1)
    clip=t*t*(3-2*t)
    yy,xx=np.mgrid[0:h,0:w].astype(np.float32)
    px=(xx+.5)/w; py=(yy+.5)/h
    target_size=(data['mask_width'],data['mask_height'])
    def save_tinted(alpha: np.ndarray, color: str, name: str, size=target_size) -> None:
        # Resize alpha alone; keep constant unpremultiplied RGB even where alpha
        # is zero, preventing a black fringe under texture filtering.
        ai=Image.fromarray(np.rint(np.clip(alpha,0,1)*255).astype(np.uint8)).resize(size,Image.Resampling.LANCZOS)
        a=np.asarray(ai)
        rr=np.zeros((size[1],size[0],4),dtype=np.uint8)
        rr[:,:,:3]=[int(color[i:i+2],16) for i in (1,3,5)]
        rr[:,:,3]=a
        Image.fromarray(rr).save(dst/name,optimize=True)
    for kind,definitions in [('band',data['bands']),('tone',data['tones'])]:
        for i,definition in enumerate(definitions):
            # Union of lobes is bounded by 1, so overlapping zones don't saturate.
            field=np.zeros((h,w),dtype=np.float32)
            for lobe in definition['lobes']:
                cx,cy,sx,sy,angle,amount=lobe['gaussian']
                # Rotate in source pixel coordinates, not in a distorted unit square.
                dx=(px-cx)*w; dy=(py-cy)*h
                theta=np.deg2rad(angle); ca=np.cos(theta); sa=np.sin(theta)
                ax=ca*dx+sa*dy; ay=-sa*dx+ca*dy
                g=amount*np.exp(-.5*((ax/(sx*w))**2+(ay/(sy*h))**2))
                field=1-(1-field)*(1-g)
            save_tinted(field*clip,definition['color'],f'{kind}_{i}.png')
    # Black body-only backing, transparent surroundings, and registered line art.
    save_tinted(body.astype(np.float32),'#000000','body_backing.png')
    # Unmatte from black. Multiplying this RGB by alpha reconstructs the original
    # nonblack RGB values to rounding accuracy, without a dark edge on a glow.
    alpha=rgb.max(axis=2)/255.0
    normalized=np.zeros_like(rgb)
    np.divide(rgb,alpha[:,:,None],out=normalized,where=alpha[:,:,None]>0)
    outline=np.empty((h,w,4),dtype=np.uint8)
    outline[:,:,:3]=np.rint(np.clip(normalized,0,255)).astype(np.uint8)
    outline[:,:,3]=np.rint(alpha*255).astype(np.uint8)
    Image.fromarray(outline).save(dst/'body_outline.png',optimize=True)
    src.save(dst/'opaque_reference.png',optimize=True)
    Image.fromarray(np.uint8(body)*255).save(dst/'silhouette_debug.png')
    write_header(data,ROOT/'src/vtune/BodyMapData.hpp')
    manifest={p.name:dict(bytes=p.stat().st_size,sha256=hashlib.sha256(p.read_bytes()).hexdigest())
              for p in sorted(dst.glob('*.png'))}
    (dst/'asset_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print(f'Baked {len(manifest)} RGBA/debug images, source {w}x{h}; glow masks {target_size}.')

if __name__=='__main__':
    main()
