// Generated by tools/build_assets.py. Edit definition.json, not this file.
#pragma once
#include <array>
#include <cstddef>
namespace vtune_body {
constexpr std::size_t kBandCount = 7;
constexpr std::size_t kToneCount = 7;
constexpr std::size_t kLayerCount = kBandCount + kToneCount;
struct BandDefinition { float lowHz, highHz; const char* label; const char* asset; };
struct ToneDefinition { float frequencyHz; const char* label; const char* asset; };
constexpr float kSourceWidth = 788.f;
constexpr float kSourceHeight = 1002.f;
constexpr float kMinHz = 20.f;
constexpr float kMaxHz = 2000.f;
constexpr float kBoundaryHalfWidthOctaves = 0.08f;
constexpr float kToneSupportCents = 70.f;
constexpr float kSmoothingSeconds = 0.09f;
constexpr float kDefaultOpacity = 0.6f;
constexpr float kCombinedReportGain = 0.55f;
constexpr float kCombinedSymbolicGain = 0.9f;
static constexpr std::array<BandDefinition, kBandCount> kBands = {{
    {20.f, 30.f, "20–30 Hz · chest, abdomen, eyes / ears", "res/VTune/body-map/band_0.png"},
    {30.f, 50.f, "30–50 Hz · spine, core, legs", "res/VTune/body-map/band_1.png"},
    {50.f, 100.f, "50–100 Hz · larger muscle groups", "res/VTune/body-map/band_2.png"},
    {100.f, 300.f, "100–300 Hz · throat, chest, abdomen / flanks", "res/VTune/body-map/band_3.png"},
    {300.f, 600.f, "300–600 Hz · head and upper neck", "res/VTune/body-map/band_4.png"},
    {600.f, 1000.f, "600–1000 Hz · upper / central head", "res/VTune/body-map/band_5.png"},
    {1000.f, 2000.f, "1000–2000 Hz · ears and head", "res/VTune/body-map/band_6.png"},
}};
static constexpr std::array<ToneDefinition, kToneCount> kTones = {{
    {396.f, "396 Hz · Root", "res/VTune/body-map/tone_0.png"},
    {417.f, "417 Hz · Sacral", "res/VTune/body-map/tone_1.png"},
    {528.f, "528 Hz · Solar plexus", "res/VTune/body-map/tone_2.png"},
    {639.f, "639 Hz · Heart", "res/VTune/body-map/tone_3.png"},
    {741.f, "741 Hz · Throat", "res/VTune/body-map/tone_4.png"},
    {852.f, "852 Hz · Third eye", "res/VTune/body-map/tone_5.png"},
    {963.f, "963 Hz · Upper head / unity motif", "res/VTune/body-map/tone_6.png"},
}};
} // namespace vtune_body
