#!/usr/bin/env python3
"""Generate deterministic clean-room PHONEX corpus data.

Phase 1 establishes the generator contract and provenance inputs. Synthetic
phoneme prototypes and bundled scripts are added in Phase 4.
"""

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "PhonexRomData.inc"
INPUT_DIR = ROOT / "tools" / "phonex_rom"
INPUTS = ("phonemes.json", "pronunciations.tsv", "bundled_phrases.tsv", "PROVENANCE.md")


def render() -> str:
    for name in INPUTS:
        path = INPUT_DIR / name
        if not path.is_file():
            raise ValueError(f"missing corpus source: {path.relative_to(ROOT)}")
    provenance = (INPUT_DIR / "PROVENANCE.md").read_text(encoding="utf-8").strip()
    if not provenance:
        raise ValueError("PHONEX corpus provenance must not be empty")
    return """// Generated by tools/generate_phonex_rom.py. Do not edit.\n\nnamespace phonex {\nconstexpr unsigned kRomSchemaVersion = 1u;\nconstexpr unsigned kGeneratedPhoneCount = 0u;\nconstexpr unsigned kGeneratedPhraseCount = 0u;\n} // namespace phonex\n"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        generated = render()
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != generated:
            print(f"stale generated file: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("PHONEX ROM data is deterministic and current")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
