#!/usr/bin/env python3
"""Generate Mandelwake's version-one deterministic lookup tables."""

from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path
import struct
import sys


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "MandelwakeTables.hpp"


def round_half_away_positive(value: float) -> int:
    if not math.isfinite(value) or value < 0.0:
        raise ValueError(f"expected finite non-negative value, got {value!r}")
    return int(math.floor(value + 0.5))


def digest_i32(values: list[int]) -> str:
    payload = b"".join(struct.pack("<i", value) for value in values)
    return hashlib.sha256(payload).hexdigest()


def digest_u32(values: list[int]) -> str:
    payload = b"".join(struct.pack("<I", value) for value in values)
    return hashlib.sha256(payload).hexdigest()


def format_values(values: list[int], indent: str = "\t", per_line: int = 8) -> str:
    lines: list[str] = []
    for start in range(0, len(values), per_line):
        chunk = values[start : start + per_line]
        suffix = "," if start + per_line < len(values) else ""
        lines.append(indent + ", ".join(str(value) for value in chunk) + suffix)
    return "\n".join(lines)


def generate_text() -> str:
    q28_scale = 1 << 28
    q30_scale = 1 << 30

    zoom = [
        round_half_away_positive((2.0 ** (-index / 256.0)) * q28_scale)
        for index in range(3073)
    ]

    rate_min_index = -1619
    rate_max_index = 1445
    rate = []
    for index in range(rate_min_index, rate_max_index + 1):
        hz = max(0.05, min(200.0, 4.0 * (2.0 ** (index / 256.0))))
        rate.append(round_half_away_positive(hz * 1_000_000.0))

    phase = [
        round_half_away_positive(
            math.atan(index / 4096.0) / math.pi * q30_scale
        )
        for index in range(4097)
    ]

    zoom_digest = digest_i32(zoom)
    rate_digest = digest_u32(rate)
    phase_digest = digest_i32(phase)

    return f"""// Generated by tools/generate_mandelwake_tables.py. Do not edit by hand.
#pragma once

#include <array>
#include <cstdint>

namespace mandelwake {{

constexpr int kZoomTableSize = {len(zoom)};
constexpr int kRateTableMinIndex = {rate_min_index};
constexpr int kRateTableMaxIndex = {rate_max_index};
constexpr int kRateTableSize = {len(rate)};
constexpr int kPhaseAtanTableSize = {len(phase)};

constexpr const char kZoomTableSha256[] = "{zoom_digest}";
constexpr const char kRateTableSha256[] = "{rate_digest}";
constexpr const char kPhaseAtanTableSha256[] = "{phase_digest}";

constexpr std::array<std::int32_t, kZoomTableSize> kZoomScaleQ28 {{{{
{format_values(zoom)}
}}}};

constexpr std::array<std::uint32_t, kRateTableSize> kRateMicroHz {{{{
{format_values(rate)}
}}}};

constexpr std::array<std::int32_t, kPhaseAtanTableSize> kPhaseAtanQ30 {{{{
{format_values(phase)}
}}}};

}} // namespace mandelwake
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the checked-in header without rewriting it",
    )
    args = parser.parse_args()

    expected = generate_text()
    if args.check:
        if not OUTPUT.exists():
            print(f"missing generated table header: {OUTPUT}", file=sys.stderr)
            return 1
        actual = OUTPUT.read_text(encoding="utf-8")
        if actual != expected:
            print(
                "Mandelwake table header is stale; run "
                "tools/generate_mandelwake_tables.py",
                file=sys.stderr,
            )
            return 1
        print("Mandelwake lookup tables and checksums are current")
        return 0

    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
