"""Export the audited MG204 control tables as C++11 binary32 constants."""
import csv
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / 'firmware/Morphagene/tables'
OUT = ROOT / 'src/ChimeraFirmwareTables.hpp'

def main():
    lines = ['// Generated by tools/generate_chimera_firmware_tables.py.',
             '// MG204 application SHA256: 44037eb2cf24b5fc411135e487a6fa226498a8478db981659bb53341cb967609',
             '// Source: firmware/Morphagene/tables; preserve ROM values, not fitted curves.',
             '#pragma once', '#include <array>',
             'namespace chimera { namespace firmware {']
    for name in ('gene_size_exp', 'varispeed_magnitude', 'varispeed_positive', 'morph_launch', 'morph_density', 'morph_gain'):
        rows = list(csv.DictReader((TABLES / (name + '.csv')).open()))
        values = []
        for row in rows:
            value = float(row['value'])
            assert struct.unpack('<I', struct.pack('<f', value))[0] == int(row['bits_hex'], 16)
            literal = format(value, '.9g')
            if '.' not in literal and 'e' not in literal:
                literal += '.0'
            values.append(literal + 'f')
        lines.append('static const std::array<float, %d> %s = {{' % (len(values), name))
        lines.extend('    ' + ', '.join(values[i:i+6]) + ',' for i in range(0, len(values), 6))
        lines.append('}};')
    lines.extend(['// Default chord third ratio is the ROM word 0x3faaaaaa.',
                  'static constexpr float defaultChordThird = 1.3333332538604736f;',
                  '// Interior of the +1x / -1x bins in both bidirectional modes.',
                  'static constexpr float forwardUnityKnob = 0.8625f;',
                  'static constexpr float reverseUnityKnob = 0.1325f;',
                  '} }', ''])
    OUT.write_text('\n'.join(lines), encoding='utf-8')

if __name__ == '__main__':
    main()
