// Generated by tools/generate_panel_anchor_atlas.py. Do not edit by hand.
#include "PanelAnchorAtlas.hpp"

#include <algorithm>
#include <cstdint>
#include <fstream>
#include <limits>
#include <sstream>
#include <string>

#include <unordered_map>
#include <vector>

namespace panel_svg {
namespace {

constexpr uint32_t kAnchorHasCenter = 1u << 0;
constexpr uint32_t kAnchorHasRect = 1u << 1;
constexpr uint32_t kAnchorHasRadius = 1u << 2;
constexpr uint64_t kFnv64Offset = 14695981039346656037ull;
constexpr uint64_t kFnv64Prime = 1099511628211ull;

struct SvgAtlasRecord { const char* path; uint64_t size; uint64_t fnv64; };
struct AnchorAtlasRecord { uint16_t svgIndex; const char* id; uint32_t flags; float cx; float cy; float x; float y; float width; float height; float radius; };

static const SvgAtlasRecord kSvgAtlas[] = {
	{"res/BananutBlack.svg", 5275ull, 0xedcd7926be8de7ecull},
	{"res/bifurx.svg", 72184ull, 0x2a41d9c56e4fe8e8ull},
	{"res/blank.svg", 21648ull, 0x5d682cc9d0d5089full},
	{"res/bulkhead.svg", 16553ull, 0x95702365aac0f428ull},
	{"res/chess.svg", 41960ull, 0x4fe61040f37916eeull},
	{"res/chronomaw.svg", 48823ull, 0xb5e622b5073d677eull},
	{"res/crownstep.svg", 80614ull, 0x276429bdb533ba55ull},
	{"res/deck.svg", 137860ull, 0x8d5cf0b3c4012fbfull},
	{"res/flux.svg", 212125ull, 0x25488bc268ea87b4ull},
	{"res/proc.svg", 96061ull, 0x6a56aae945e9545bull},
	{"res/sil.svg", 137528ull, 0x1983fe15ab63ac72ull},
	{"res/tdscope.svg", 82905ull, 0xda06b2fa7a1b9be8ull},
	{"res/undertow.svg", 90762ull, 0x0588a08ba39e38cbull},
	{"res/Vahdrim'Keth.svg", 6757ull, 0x7933dbdd114343ceull},
	{"res/wyrm.svg", 82953ull, 0xd8050c9718972665ull},
};

static const AnchorAtlasRecord kAnchorAtlas[] = {
	{1, "black_background", 3u, 4553.82826f, 7441.0425f, 986.18201f, 997.229f, 7135.2925f, 12887.627f, 0.f},
	{1, "gray_outline", 3u, 6082.8187f, 7441.0425f, 1096.182f, 1107.229f, 9973.2734f, 12667.627f, 0.f},
	{1, "frame_left", 3u, 3540.2017f, 9965.42945f, 57.409203f, 7794.9995f, 6965.585f, 4340.8599f, 0.f},
	{1, "outputs", 3u, 4513.5499f, 11506.2505f, 3974.6584f, 10837.059f, 1077.783f, 1338.3831f, 0.f},
	{1, "outputs-3", 3u, 4514.64884f, 11511.3498f, 4042.1721f, 10894.673f, 944.95349f, 1233.3535f, 0.f},
	{1, "MODE_PARAM", 1u, 1150.0443f, 7570.0098f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "MODE_MENU_BUTTON", 1u, 313.15613f, 7570.0098f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "LEVEL_PARAM", 1u, 1651.4443f, 8760.0117f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "RESO_PARAM", 1u, 1651.4443f, 10295.81f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "FREQ_PARAM", 5u, 3546.f, 10160.f, 0.f, 0.f, 0.f, 0.f, 520.f},
	{1, "TITO_PARAM", 1u, 3542.3442f, 8585.21f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "SPAN_PARAM", 1u, 5451.3442f, 8760.0098f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "BALANCE_PARAM", 1u, 5451.3232f, 10295.81f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "FM_AMT_PARAM", 3u, 680.f, 9510.f, 550.f, 8110.f, 260.f, 2800.f, 0.f},
	{1, "SPAN_CV_ATTEN_PARAM", 3u, 6402.f, 9510.f, 6272.f, 8110.f, 260.f, 2800.f, 0.f},
	{1, "FM_AMT_LIGHT", 1u, 680.f, 7980.0312f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "SPAN_CV_ATTEN_LIGHT", 1u, 6402.f, 7980.0312f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "IN_INPUT", 1u, 2589.9988f, 11389.972f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "VOCT_INPUT", 1u, 3544.9988f, 11389.972f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "FM_INPUT", 1u, 679.99866f, 11389.972f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "RESO_CV_INPUT", 1u, 1634.9987f, 11389.972f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "BALANCE_CV_INPUT", 1u, 5454.9985f, 11389.972f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "SPAN_CV_INPUT", 1u, 6409.9985f, 11389.972f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "OUT_OUTPUT", 1u, 4509.9985f, 11389.972f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{1, "SPECTRUM", 3u, 3553.84866f, 4168.84985f, 78.833763f, 1055.0354f, 6950.0298f, 6227.6289f, 0.f},
	{2, "black_background", 3u, 6082.81901f, 7441.0425f, 986.18201f, 997.229f, 10193.274f, 12887.627f, 0.f},
	{2, "gray_outline", 3u, 6082.8187f, 7441.0425f, 1096.182f, 1107.229f, 9973.2734f, 12667.627f, 0.f},
	{2, "LIN_LOG_1", 1u, 1397.5443f, 5052.6074f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "FALL_1", 1u, 4200.748f, 5307.9067f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CYCLE_1", 1u, 3187.5281f, 2093.8098f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "RISE_1", 1u, 3375.4507f, 3629.2629f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "EoR_CH_1", 1u, 1653.6869f, 9676.0312f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "Light_Unity_1", 1u, 1654.6868f, 11075.845f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "EOR_1", 1u, 1003.6987f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CH_1_Unity", 1u, 1004.7076f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "INPUT_1_TRIG", 1u, 2091.1169f, 1535.3943f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CH1_CYCLE_CV", 1u, 4004.8987f, 2083.7886f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CH1_FALL_CV", 1u, 3270.4065f, 6326.3164f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CH1_BOTH_CV", 1u, 2663.2986f, 5026.9717f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CH1_RISE_CV", 1u, 2168.2986f, 3641.5715f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "INPUT_1", 1u, 994.70752f, 1535.3943f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CYCLE_1_LED", 1u, 3187.5261f, 1485.5403f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "EoC_CH_4", 1u, 8467.9873f, 9671.5703f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "Light_Unity_4", 1u, 8473.0996f, 11075.831f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CYCLE_4_LED", 1u, 6935.2524f, 1485.5403f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CYCLE_4", 1u, 6955.2441f, 2093.8098f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "EOC_4", 1u, 9128.1035f, 9691.5117f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CH_4_Unity", 1u, 9128.1035f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CH4_CYCLE_CV", 1u, 6117.8989f, 2083.7886f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CH4_FALL_CV", 1u, 6918.9263f, 6326.3164f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CH4_BOTH_CV", 1u, 7455.9863f, 5006.9717f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CH4_RISE_CV", 1u, 7980.9985f, 3621.5715f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "INPUT_4", 1u, 9118.1035f, 1535.3943f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "INPUT_4_TRIG", 1u, 8021.6948f, 1535.3943f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "LIN_LOG_4", 1u, 9171.5977f, 5035.7666f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "FALL_4", 1u, 5918.5444f, 5307.9067f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "RISE_4", 1u, 6763.814f, 3629.2629f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "INPUT_3", 1u, 5958.4985f, 7637.6924f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "INPUT_2", 1u, 4254.2988f, 7637.7334f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "INV_LED", 1u, 5955.3867f, 11075.831f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "INV_OUT", 1u, 6797.499f, 11088.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "SUM_OUT", 1u, 5071.3989f, 11088.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "OR_OUT", 1u, 3365.1987f, 11088.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "OR_LED", 1u, 4237.3867f, 11075.831f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "ATTENUATE_4", 1u, 7593.1445f, 8644.5771f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "ATTENUATE_3", 1u, 5958.5444f, 8644.5771f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "ATTENUATE_2", 1u, 4254.2441f, 8644.5771f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "ATTENUATE_1", 1u, 2549.4443f, 8644.5771f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "OUT_4", 1u, 7583.2007f, 9691.5117f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "OUT_3", 1u, 5948.5542f, 9691.5117f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "OUT_2", 1u, 4234.2988f, 9691.5117f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "OUT_1", 1u, 2529.5142f, 9691.5117f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{2, "CH1_PREVIEW", 3u, 1436.00009f, 6950.0022f, 198.16904f, 6212.1689f, 2475.6621f, 1475.6666f, 0.f},
	{3, "black_background", 3u, 5063.49156f, 7441.0425f, 986.18201f, 997.229f, 8154.6191f, 12887.627f, 0.f},
	{3, "room_canvas_frame", 3u, 4065.04982f, 4568.95015f, 98.713165f, 1043.8132f, 7932.6733f, 7050.2739f, 0.f},
	{3, "decay_knob_art", 5u, 700.f, 8170.f, 0.f, 0.f, 0.f, 0.f, 205.f},
	{3, "diffuse_knob_art", 5u, 2035.f, 8170.f, 0.f, 0.f, 0.f, 0.f, 205.f},
	{3, "mix_knob_art", 5u, 3370.f, 8170.f, 0.f, 0.f, 0.f, 0.f, 205.f},
	{3, "absorb_knob_art", 5u, 4705.f, 8170.f, 0.f, 0.f, 0.f, 0.f, 205.f},
	{3, "motion_knob_art", 5u, 7375.f, 8170.f, 0.f, 0.f, 0.f, 0.f, 205.f},
	{3, "lst_x_jack_art", 5u, 900.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "lst_y_jack_art", 5u, 1940.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "wall_left_jack_art", 5u, 2980.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "wall_right_jack_art", 5u, 4020.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "wall_front_jack_art", 5u, 5060.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "wall_back_jack_art", 5u, 6100.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "in_l_jack_art", 5u, 900.f, 11350.f, 0.f, 0.f, 0.f, 0.f, 195.f},
	{3, "in_r_jack_art", 5u, 1940.f, 11350.f, 0.f, 0.f, 0.f, 0.f, 195.f},
	{3, "out_l_jack_art", 5u, 6100.f, 11350.f, 0.f, 0.f, 0.f, 0.f, 195.f},
	{3, "out_r_jack_art", 5u, 7228.f, 11350.f, 0.f, 0.f, 0.f, 0.f, 195.f},
	{3, "room_canvas", 3u, 4065.00169f, 4568.983f, 77.542442f, 1015.0897f, 7974.9185f, 7107.7866f, 0.f},
	{3, "decay_param", 5u, 700.f, 9000.f, 0.f, 0.f, 0.f, 0.f, 205.f},
	{3, "diffuse_param", 5u, 2035.f, 9000.f, 0.f, 0.f, 0.f, 0.f, 205.f},
	{3, "mix_param", 5u, 3370.f, 9000.f, 0.f, 0.f, 0.f, 0.f, 205.f},
	{3, "absorb_param", 5u, 4705.f, 9000.f, 0.f, 0.f, 0.f, 0.f, 205.f},
	{3, "motion_param", 5u, 7375.f, 9000.f, 0.f, 0.f, 0.f, 0.f, 205.f},
	{3, "lst_x_input", 5u, 900.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "lst_y_input", 5u, 1940.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "wall_left_input", 5u, 2980.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "wall_right_input", 5u, 4020.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "wall_front_input", 5u, 5060.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "wall_back_input", 5u, 6100.f, 10350.f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{3, "in_l_input", 5u, 900.f, 11350.f, 0.f, 0.f, 0.f, 0.f, 195.f},
	{3, "in_r_input", 5u, 1940.f, 11350.f, 0.f, 0.f, 0.f, 0.f, 195.f},
	{3, "out_l_output", 5u, 6100.f, 11350.f, 0.f, 0.f, 0.f, 0.f, 195.f},
	{3, "out_r_output", 5u, 7228.f, 11350.f, 0.f, 0.f, 0.f, 0.f, 195.f},
	{5, "black_background", 3u, 11179.4565f, 7441.0425f, 986.18201f, 997.229f, 20386.549f, 12887.627f, 0.f},
	{5, "gray_outline", 3u, 6082.8187f, 7441.0425f, 1096.182f, 1107.229f, 9973.2734f, 12667.627f, 0.f},
	{5, "GLOBAL_BAR_RECT", 3u, 10071.2718f, 1888.5481f, 1711.6323f, 1077.0962f, 16719.279f, 1622.9038f, 0.f},
	{5, "OVERVIEW_RECT", 3u, 2825.4297f, 7400.00095f, 1722.9038f, 2800.3608f, 2205.0518f, 9199.2803f, 0.f},
	{5, "TIMELINE_RECT", 3u, 11213.7977f, 4816.90725f, 4028.6772f, 2822.543f, 14370.241f, 3988.7285f, 0.f},
	{5, "INSPECTOR_RECT", 3u, 11224.8897f, 9461.27145f, 4028.6772f, 6945.0859f, 14392.425f, 5032.3711f, 0.f},
	{5, "RUN", 5u, 2700.f, 1600.f, 0.f, 0.f, 0.f, 0.f, 295.f},
	{5, "BPM", 5u, 4700.f, 1600.f, 0.f, 0.f, 0.f, 0.f, 295.f},
	{5, "ACTIVE_BANK", 5u, 6700.f, 1600.f, 0.f, 0.f, 0.f, 0.f, 295.f},
	{5, "LOAD_BANK", 5u, 8800.f, 1600.f, 0.f, 0.f, 0.f, 0.f, 295.f},
	{5, "SAVE_BANK", 5u, 9800.f, 1600.f, 0.f, 0.f, 0.f, 0.f, 295.f},
	{5, "SELECTED_OUTPUT", 5u, 13300.f, 1600.f, 0.f, 0.f, 0.f, 0.f, 295.f},
	{5, "CLK_INPUT", 5u, 950.f, 2200.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "RUN_INPUT", 5u, 950.f, 3550.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "RESET_INPUT", 5u, 950.f, 4900.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "CV_1_INPUT", 5u, 950.f, 6700.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "CV_2_INPUT", 5u, 950.f, 8050.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "CV_3_INPUT", 5u, 950.f, 9400.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "CV_4_INPUT", 5u, 950.f, 10750.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "OUT_1_OUTPUT", 5u, 19350.f, 1850.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "OUT_2_OUTPUT", 5u, 19350.f, 3150.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "OUT_3_OUTPUT", 5u, 19350.f, 4450.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "OUT_4_OUTPUT", 5u, 19350.f, 5750.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "OUT_5_OUTPUT", 5u, 19350.f, 7050.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "OUT_6_OUTPUT", 5u, 19350.f, 8350.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "OUT_7_OUTPUT", 5u, 19350.f, 9650.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "OUT_8_OUTPUT", 5u, 19350.f, 10950.f, 0.f, 0.f, 0.f, 0.f, 398.f},
	{5, "RUN_LIGHT", 5u, 3250.f, 1600.f, 0.f, 0.f, 0.f, 0.f, 120.f},
	{5, "SYNC_LIGHT", 5u, 17300.f, 1600.f, 0.f, 0.f, 0.f, 0.f, 120.f},
	{5, "OUT_1_LIGHT", 5u, 18720.f, 1850.f, 0.f, 0.f, 0.f, 0.f, 120.f},
	{5, "OUT_2_LIGHT", 5u, 18720.f, 3150.f, 0.f, 0.f, 0.f, 0.f, 120.f},
	{5, "OUT_3_LIGHT", 5u, 18720.f, 4450.f, 0.f, 0.f, 0.f, 0.f, 120.f},
	{5, "OUT_4_LIGHT", 5u, 18720.f, 5750.f, 0.f, 0.f, 0.f, 0.f, 120.f},
	{5, "OUT_5_LIGHT", 5u, 18720.f, 7050.f, 0.f, 0.f, 0.f, 0.f, 120.f},
	{5, "OUT_6_LIGHT", 5u, 18720.f, 8350.f, 0.f, 0.f, 0.f, 0.f, 120.f},
	{5, "OUT_7_LIGHT", 5u, 18720.f, 9650.f, 0.f, 0.f, 0.f, 0.f, 120.f},
	{5, "OUT_8_LIGHT", 5u, 18720.f, 10950.f, 0.f, 0.f, 0.f, 0.f, 120.f},
	{6, "black_background", 3u, 5573.15566f, 7441.0425f, 986.18201f, 997.229f, 9173.9473f, 12887.627f, 0.f},
	{6, "gray_outline", 3u, 6082.8187f, 7441.0425f, 1096.182f, 1107.229f, 9973.2734f, 12667.627f, 0.f},
	{6, "frame_left", 3u, 3205.22555f, 12645.7885f, 1026.0244f, 12044.202f, 4358.4023f, 1203.173f, 0.f},
	{6, "outputs", 3u, 7947.1697f, 12637.9656f, 5769.2461f, 12037.65f, 4355.8472f, 1200.6312f, 0.f},
	{6, "outputs-3", 3u, 5575.71205f, 11426.309f, 1010.9381f, 10831.871f, 9129.5479f, 1188.876f, 0.f},
	{6, "SEQ_LENGTH_PARAM", 5u, 330.28824f, 12531.324f, 0.f, 0.f, 0.f, 0.f, 295.f},
	{6, "NEW_GAME_PARAM", 5u, 7390.f, 365.5f, 0.f, 0.f, 0.f, 0.f, 170.f},
	{6, "CLOCK_INPUT", 1u, 528.70001f, 11465.241f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{6, "RESET_INPUT", 1u, 1629.4414f, 11465.241f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{6, "TRANSPOSE_INPUT", 1u, 2788.1436f, 11465.241f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{6, "ROOT_INPUT", 1u, 3878.885f, 11465.241f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{6, "PITCH_OUTPUT", 1u, 7545.2002f, 11465.241f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{6, "ACCENT_OUTPUT", 1u, 5360.5f, 11465.241f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{6, "MOD_OUTPUT", 1u, 8615.083f, 11465.241f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{6, "EOC_OUTPUT", 1u, 6461.8003f, 11465.241f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{6, "HUMAN_TURN_LIGHT", 1u, 4570.2002f, 11457.4f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{6, "AI_TURN_LIGHT", 1u, 4570.2002f, 11751.306f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{6, "STEP_COUNTER", 3u, 4572.1002f, 10386.9f, 28.400002f, 9780.5f, 9087.4004f, 1212.8f, 0.f},
	{6, "BOARD_AREA", 3u, 4582.f, 5330.f, 142.f, 890.f, 8880.f, 8880.f, 0.f},
	{7, "black_background", 3u, 50.965f, 64.249975f, 0.f, 3.5527137e-15f, 101.93f, 128.49995f, 0.f},
	{7, "rect1529", 3u, 50.8f, 64.25f, 0.f, 0.f, 101.6f, 128.5f, 0.f},
	{7, "gray_border_inner", 3u, 50.800001f, 64.25f, 1.6f, 1.6f, 98.400002f, 125.3f, 0.f},
	{7, "rect1631", 3u, 33.3584991f, 107.130436f, 2.2390001f, 93.082001f, 62.238998f, 28.096869f, 0.f},
	{7, "rect1633", 3u, 88.552428f, 107.257134f, 77.14624f, 93.317749f, 22.812376f, 27.878769f, 0.f},
	{7, "BUFFER", 5u, 8.4081755f, 17.086493f, 0.f, 0.f, 0.f, 0.f, 4.f},
	{7, "RATE", 5u, 20.889322f, 99.225998f, 0.f, 0.f, 0.f, 0.f, 4.f},
	{7, "SENSITIVITY", 5u, 7.4590001f, 84.669998f, 0.f, 0.f, 0.f, 0.f, 4.f},
	{7, "MIX", 5u, 70.982445f, 98.871986f, 0.f, 0.f, 0.f, 0.f, 4.f},
	{7, "FEEDBACK", 5u, 70.982002f, 112.99601f, 0.f, 0.f, 0.f, 0.f, 4.f},
	{7, "FREEZE", 5u, 57.499905f, 101.10004f, 0.f, 0.f, 0.f, 0.f, 4.f},
	{7, "REVERSE", 5u, 45.599949f, 101.10004f, 0.f, 0.f, 0.f, 0.f, 4.f},
	{7, "SLIP", 5u, 17.700226f, 86.799683f, 0.f, 0.f, 0.f, 0.f, 4.f},
	{7, "FREEZE_LIGHT", 5u, 57.499905f, 95.300003f, 0.f, 0.f, 0.f, 0.f, 1.45f},
	{7, "REVERSE_LIGHT", 5u, 45.599949f, 95.300003f, 0.f, 0.f, 0.f, 0.f, 1.45f},
	{7, "SLIP_LIGHT", 5u, 17.700226f, 82.399651f, 0.f, 0.f, 0.f, 0.f, 1.45f},
	{7, "POSITION_CV", 5u, 45.665001f, 112.89996f, 0.f, 0.f, 0.f, 0.f, 4.1500001f},
	{7, "RATE_CV", 5u, 20.905001f, 112.89996f, 0.f, 0.f, 0.f, 0.f, 4.1500001f},
	{7, "INPUT_R", 5u, 8.4780197f, 112.89996f, 0.f, 0.f, 0.f, 0.f, 4.1500001f},
	{7, "INPUT_L", 5u, 8.4370003f, 99.012131f, 0.f, 0.f, 0.f, 0.f, 4.1500001f},
	{7, "SCRATCH_GATE", 5u, 33.403f, 112.89996f, 0.f, 0.f, 0.f, 0.f, 4.1500001f},
	{7, "FREEZE_GATE", 5u, 57.499981f, 112.89996f, 0.f, 0.f, 0.f, 0.f, 4.1500001f},
	{7, "REV_CV", 5u, 33.403f, 101.25f, 0.f, 0.f, 0.f, 0.f, 4.1500001f},
	{7, "OUTPUT_L", 5u, 94.241013f, 99.012001f, 0.f, 0.f, 0.f, 0.f, 4.1500001f},
	{7, "OUTPUT_R", 5u, 94.199997f, 113.146f, 0.f, 0.f, 0.f, 0.f, 4.1500001f},
	{7, "S_GATE_O", 5u, 83.03685f, 99.135414f, 0.f, 0.f, 0.f, 0.f, 4.1500001f},
	{7, "S_POS_O", 5u, 82.995834f, 113.26942f, 0.f, 0.f, 0.f, 0.f, 4.1500001f},
	{7, "CARTRIDGE_CYCLE", 5u, 92.279999f, 66.561996f, 0.f, 0.f, 0.f, 0.f, 1.9f},
	{7, "TD_SCOPE_SPAWN", 5u, 98.5f, 34.900002f, 0.f, 0.f, 0.f, 0.f, 1.9f},
	{7, "PLATTER_AREA", 5u, 50.799999f, 53.971752f, 0.f, 0.f, 0.f, 0.f, 37.031235f},
	{8, "black_background", 3u, 6082.81901f, 7441.0425f, 986.18201f, 997.229f, 10193.274f, 12887.627f, 0.f},
	{8, "gray_outline", 3u, 6082.8187f, 7441.0425f, 1096.182f, 1107.229f, 9973.2734f, 12667.627f, 0.f},
	{8, "frame_left", 3u, 3603.3966f, 4914.86715f, 1274.3661f, 2060.8857f, 4658.061f, 5707.9629f, 0.f},
	{8, "frame_input_2", 3u, 4934.06945f, 8512.137f, 4149.1533f, 7895.5234f, 1569.8323f, 1233.2272f, 0.f},
	{8, "frame_input_3", 3u, 7116.49345f, 8512.1199f, 6376.6152f, 7895.4141f, 1479.7565f, 1233.4116f, 0.f},
	{8, "frame_right", 3u, 8556.8452f, 4914.8501f, 6231.374f, 2061.0166f, 4650.9424f, 5707.667f, 0.f},
	{8, "outputs", 3u, 6082.81905f, 11638.466f, 1381.7048f, 10215.551f, 9402.2285f, 2845.8301f, 0.f},
	{8, "LIN_LOG_1", 1u, 1397.5443f, 5052.6074f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "FALL_1", 1u, 4200.748f, 5307.9067f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CYCLE_1", 1u, 2837.5388f, 2093.8098f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "RISE_1", 1u, 3375.4507f, 3641.5715f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "EoR_CH_1", 1u, 1654.6868f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "Light_Unity_1", 1u, 1654.6868f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "EOR_1", 1u, 1003.6987f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CH_1_Unity", 1u, 1004.7076f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "INPUT_1_TRIG", 1u, 1791.0962f, 1535.3943f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CH1_CYCLE_CV", 1u, 3654.9094f, 2083.7886f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CH1_FALL_CV", 1u, 3270.4065f, 6326.3164f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CH1_BOTH_CV", 1u, 2663.2986f, 5026.9717f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CH1_RISE_CV", 1u, 2168.2986f, 3641.5715f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "INPUT_1", 1u, 794.69867f, 1535.3943f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CYCLE_1_LED", 1u, 2837.5369f, 1485.5403f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "EoC_CH_4", 1u, 8467.9873f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "Light_Unity_4", 1u, 8467.9873f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CYCLE_4_LED", 1u, 7285.2383f, 1485.5308f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CYCLE_4", 1u, 7305.23f, 2093.8003f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "EOC_4", 1u, 9128.1035f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CH_4_Unity", 1u, 9128.1035f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CH4_CYCLE_CV", 1u, 6467.8848f, 2083.7791f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CH4_FALL_CV", 1u, 6918.9263f, 6326.3164f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CH4_BOTH_CV", 1u, 7455.9863f, 5026.9717f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CH4_RISE_CV", 1u, 7980.9985f, 3641.5715f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "INPUT_4", 1u, 9318.1035f, 1535.3943f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "INPUT_4_TRIG", 1u, 8321.6797f, 1535.3943f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "LIN_LOG_4", 1u, 9171.5977f, 5052.6074f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "FALL_4", 1u, 5918.5444f, 5307.9067f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "RISE_4", 1u, 6763.814f, 3641.5715f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "INPUT_3", 1u, 5895.0049f, 7637.6924f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "INPUT_2", 1u, 4206.8096f, 7637.7334f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "INV_LED", 1u, 5939.4238f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "INV_OUT", 1u, 6797.499f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "SUM_OUT", 1u, 5081.3486f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "OR_OUT", 1u, 3365.1987f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "OR_LED", 1u, 4223.2739f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "ATTENUATE_4", 1u, 7593.1445f, 8644.5771f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "ATTENUATE_3", 1u, 5895.0049f, 8644.5771f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "ATTENUATE_2", 1u, 4206.8096f, 8644.5771f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "ATTENUATE_1", 1u, 2549.4443f, 8644.5771f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "OUT_4", 1u, 7583.2007f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "OUT_3", 1u, 5895.0049f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "OUT_2", 1u, 4206.8096f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "OUT_1", 1u, 2529.5142f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{8, "CH4_PREVIEW", 3u, 8712.49995f, 6949.99995f, 7474.6689f, 6212.1689f, 2475.6621f, 1475.6621f, 0.f},
	{8, "CH1_PREVIEW", 3u, 1436.00009f, 6950.0022f, 198.16904f, 6212.1689f, 2475.6621f, 1475.6666f, 0.f},
	{9, "black_background", 3u, 3024.83681f, 7441.0425f, 986.18201f, 997.229f, 4077.3096f, 12887.627f, 0.f},
	{9, "gray_outline", 3u, 3042.63385f, 7441.0429f, 1084.9954f, 1096.0424f, 3915.2769f, 12690.001f, 0.f},
	{9, "frame_left", 3u, 3024.83695f, 4962.06025f, 1089.2188f, 2060.8857f, 3871.2363f, 5802.3491f, 0.f},
	{9, "outputs", 3u, 3024.8369f, 11615.5526f, 1226.6439f, 10178.908f, 3596.386f, 2873.2893f, 0.f},
	{9, "ring_in1_o", 5u, 1729.1086f, 2680.4136f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{9, "ring_trig1_o", 5u, 3069.8853f, 2680.4136f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{9, "ring_loopbtn1_o", 5u, 4280.2456f, 2959.5808f, 0.f, 0.f, 0.f, 0.f, 360.f},
	{9, "ring_surgeA_o", 5u, 4207.9512f, 4650.f, 0.f, 0.f, 0.f, 0.f, 520.f},
	{9, "ring_sinkA_o", 5u, 4303.5522f, 6333.5591f, 0.f, 0.f, 0.f, 0.f, 520.f},
	{9, "ring_curveA_o-4", 1u, 2149.4373f, 6814.4219f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "ring_eor_o", 5u, 2000.f, 10730.f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{9, "ring_out1_o", 5u, 3720.4089f, 10730.f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{9, "ring_s1_o", 5u, 2000.f, 12110.747f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{9, "ring_or_o", 5u, 3716.0947f, 12130.806f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{9, "LIN_LOG_1", 1u, 1177.5327f, 5792.6074f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "AMP", 1u, 724.64429f, 2871.01f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "FALL_1", 1u, 3290.7402f, 5307.9067f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "CYCLE_1", 1u, 3307.5281f, 2013.8008f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "RISE_1", 1u, 3290.7441f, 3629.2629f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "EOR_LIGHT", 1u, 1593.6866f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "MAIN_LIGHT", 1u, 1594.6865f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "EOR_OUTPUT", 1u, 943.69867f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "MAIN_OUTPUT", 1u, 944.70752f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "TRIGGER_INPUT", 1u, 1994.2986f, 1665.4272f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "FALL_CV_INPUT", 1u, 2360.3987f, 6326.3164f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "BOTH_CV_INPUT", 1u, 1994.2986f, 4489.7715f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "RISE_CV_INPUT", 1u, 1994.2986f, 3241.5713f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "HALT_INPUT", 1u, 720.69867f, 4036.6716f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "SIGNAL_INPUT", 1u, 724.70056f, 1665.4274f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "CYCLE_LIGHT", 1u, 3307.5261f, 1405.5314f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "NEG_OUTPUT", 1u, 2655.1987f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "NEG_LIGHT", 1u, 3357.8699f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "EOC_LIGHT", 1u, 3364.5483f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "EOC_OUTPUT", 1u, 2659.5144f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{9, "CH1_PREVIEW", 3u, 2032.00003f, 7815.9582f, 217.90068f, 6991.6509f, 3628.1987f, 1648.6146f, 0.f},
	{10, "black_background", 3u, 6082.81901f, 7441.0425f, 986.18201f, 997.229f, 10193.274f, 12887.627f, 0.f},
	{10, "gray_outline", 3u, 6082.8187f, 7441.0425f, 1096.182f, 1107.229f, 9973.2734f, 12667.627f, 0.f},
	{10, "INPUT_L_INPUT", 5u, 2600.f, 11240.f, 0.f, 0.f, 0.f, 0.f, 140.f},
	{10, "INPUT_R_INPUT", 5u, 4200.f, 11240.f, 0.f, 0.f, 0.f, 0.f, 140.f},
	{10, "OUTPUT_L_OUTPUT", 5u, 5800.f, 11240.f, 0.f, 0.f, 0.f, 0.f, 140.f},
	{10, "OUTPUT_R_OUTPUT", 5u, 7400.f, 11240.f, 0.f, 0.f, 0.f, 0.f, 140.f},
	{10, "LIMITER_ACTIVE_LIGHT", 5u, 1170.f, 8070.f, 0.f, 0.f, 0.f, 0.f, 70.f},
	{10, "LOW_RECOVERY_LIGHT", 5u, 1170.f, 5004.7998f, 0.f, 0.f, 0.f, 0.f, 70.f},
	{10, "IMPACT_AIR_LIGHT", 5u, 1170.f, 5442.6855f, 0.f, 0.f, 0.f, 0.f, 70.f},
	{10, "REMOVE_MUD_LIGHT", 5u, 1170.f, 5880.5713f, 0.f, 0.f, 0.f, 0.f, 70.f},
	{10, "MID_ENHANCE_LIGHT", 5u, 1170.f, 6318.457f, 0.f, 0.f, 0.f, 0.f, 70.f},
	{10, "GLUE_COMP_LIGHT", 5u, 1170.f, 6756.3428f, 0.f, 0.f, 0.f, 0.f, 70.f},
	{10, "STEREO_ENHANCE_LIGHT", 5u, 1170.f, 7194.2285f, 0.f, 0.f, 0.f, 0.f, 70.f},
	{10, "SATURATOR_LIGHT", 5u, 1170.f, 7632.1143f, 0.f, 0.f, 0.f, 0.f, 70.f},
	{10, "MICROPEAK_LIGHT", 5u, 1170.f, 8507.8857f, 0.f, 0.f, 0.f, 0.f, 70.f},
	{10, "MASTERING_ENABLED_PARAM", 5u, 1740.f, 4390.0083f, 0.f, 0.f, 0.f, 0.f, 95.f},
	{10, "REPAIR_ENABLED_PARAM", 5u, 6950.6001f, 4390.0083f, 0.f, 0.f, 0.f, 0.f, 95.f},
	{10, "HISTOGRAM", 3u, 5083.59973f, 1752.64635f, 70.00473f, 1026.9257f, 10027.19f, 1451.4413f, 0.f},
	{10, "SPECTROGRAM_LEFT", 3u, 2563.47998f, 3274.28935f, 69.999779f, 2541.4993f, 4986.9604f, 1465.5801f, 0.f},
	{10, "SPECTROGRAM_RIGHT", 3u, 7600.7002f, 3274.28935f, 5107.2124f, 2541.4993f, 4986.9756f, 1465.5801f, 0.f},
	{11, "black_background", 3u, 3024.83681f, 7441.0425f, 986.18201f, 997.229f, 4077.3096f, 12887.627f, 0.f},
	{11, "gray_outline", 3u, 3042.63385f, 7441.0429f, 1084.9954f, 1096.0424f, 3915.2769f, 12690.001f, 0.f},
	{11, "ring_in1_o", 5u, 1729.1086f, 2680.4136f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{11, "ring_trig1_o", 5u, 3069.8853f, 2680.4136f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{11, "ring_loopbtn1_o", 5u, 4280.2456f, 2959.5808f, 0.f, 0.f, 0.f, 0.f, 360.f},
	{11, "ring_surgeA_o", 5u, 4207.9512f, 4650.f, 0.f, 0.f, 0.f, 0.f, 520.f},
	{11, "ring_sinkA_o", 5u, 4303.5522f, 6333.5591f, 0.f, 0.f, 0.f, 0.f, 520.f},
	{11, "ring_curveA_o-4", 1u, 2149.4373f, 6814.4219f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "ring_eor_o", 5u, 2000.f, 10730.f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{11, "ring_out1_o", 5u, 3720.4089f, 10730.f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{11, "ring_s1_o", 5u, 2000.f, 12110.747f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{11, "ring_or_o", 5u, 3716.0947f, 12130.806f, 0.f, 0.f, 0.f, 0.f, 454.70001f},
	{11, "LIN_LOG_1", 1u, 1177.5327f, 5792.6074f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "AMP", 1u, 724.64429f, 2871.01f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "FALL_1", 1u, 3290.7402f, 5307.9067f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "CYCLE_1", 1u, 3307.5281f, 2013.8008f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "RISE_1", 1u, 3290.7441f, 3629.2629f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "EoR_LED", 1u, 1593.6866f, 9676.0312f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "OUT_LED", 1u, 1594.6865f, 11075.845f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "EoR", 1u, 943.69867f, 9694.5723f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "OUT", 1u, 944.70752f, 11068.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "INPUT_1_TRIG", 1u, 1994.2986f, 1665.4272f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "CH1_FALL_CV", 1u, 2360.3987f, 6326.3164f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "CH1_BOTH_CV", 1u, 1994.2557f, 4489.7715f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "CH1_RISE_CV", 1u, 1994.2986f, 3241.5713f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "CV_HALT", 1u, 720.69867f, 4036.6716f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "INPUT", 1u, 724.70056f, 1665.4274f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "CYCLE_LED", 1u, 3307.5261f, 1405.5314f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "OUT_NEG", 1u, 2655.1987f, 11088.226f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "OUT_NEG_LED", 1u, 3357.8699f, 11094.092f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "EoC_LED", 1u, 3364.5483f, 9695.2383f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "EoC", 1u, 2659.5144f, 9691.5117f, 0.f, 0.f, 0.f, 0.f, 0.f},
	{11, "scope", 3u, 2039.19894f, 6565.0688f, 111.38239f, 1094.0403f, 3855.6331f, 10942.057f, 0.f},
	{11, "debug_fill", 3u, 3022.49401f, 1520.0355f, 986.18201f, 997.229f, 4072.624f, 1045.613f, 0.f},
	{12, "black_background", 3u, 3024.83681f, 7441.0425f, 986.18201f, 997.229f, 4077.3096f, 12887.627f, 0.f},
	{12, "gray_outline", 3u, 6082.8187f, 7441.0425f, 1096.182f, 1107.229f, 9973.2734f, 12667.627f, 0.f},
	{12, "outputs", 3u, 2032.00008f, 11421.4612f, 89.212578f, 10734.063f, 3885.575f, 1374.7964f, 0.f},
	{12, "frame_left", 3u, 2031.99994f, 4780.9432f, 105.75994f, 1047.9f, 3852.48f, 7466.0864f, 0.f},
	{12, "SHAPE_OUTPUT", 5u, 3280.0002f, 11280.022f, 0.f, 0.f, 0.f, 0.f, 240.f},
	{12, "SUB_OUTPUT", 5u, 2030.f, 11280.022f, 0.f, 0.f, 0.f, 0.f, 240.f},
	{12, "SINE_OUTPUT", 5u, 780.0163f, 11280.022f, 0.f, 0.f, 0.f, 0.f, 240.f},
	{12, "COARSE_PARAM", 5u, 919.9942f, 1960.0001f, 0.f, 0.f, 0.f, 0.f, 320.f},
	{12, "FINE_PARAM", 5u, 3016.7002f, 1960.0001f, 0.f, 0.f, 0.f, 0.f, 180.f},
	{12, "LIN_FM_PARAM", 5u, 860.f, 7620.0005f, 0.f, 0.f, 0.f, 0.f, 220.f},
	{12, "SHAPE_PARAM", 5u, 3136.7002f, 7620.0005f, 0.f, 0.f, 0.f, 0.f, 220.f},
	{12, "LIN_FM_INPUT", 5u, 860.f, 6248.9004f, 0.f, 0.f, 0.f, 0.f, 240.f},
	{12, "SHAPE_CV_INPUT", 5u, 3136.7002f, 6248.9004f, 0.f, 0.f, 0.f, 0.f, 240.f},
	{12, "COARSE_STEP_MODE_PARAM", 5u, 2008.3501f, 4790.f, 0.f, 0.f, 0.f, 0.f, 140.f},
	{12, "EXPO_INPUT", 5u, 2008.3501f, 6248.9004f, 0.f, 0.f, 0.f, 0.f, 240.f},
	{12, "EDGE_HARDNESS_PARAM", 5u, 2008.3501f, 7620.0005f, 0.f, 0.f, 0.f, 0.f, 140.f},
	{12, "V_OCT_INPUT", 5u, 2008.3501f, 3010.3955f, 0.f, 0.f, 0.f, 0.f, 240.f},
	{12, "SYNC_INPUT", 5u, 860.f, 4250.f, 0.f, 0.f, 0.f, 0.f, 240.f},
	{12, "S_GATE_INPUT", 5u, 3136.6833f, 4250.f, 0.f, 0.f, 0.f, 0.f, 240.f},
	{12, "SYNC_LIGHT", 5u, 1445.6001f, 4250.f, 0.f, 0.f, 0.f, 0.f, 110.f},
	{12, "S_GATE_LIGHT", 5u, 3728.8567f, 4250.f, 0.f, 0.f, 0.f, 0.f, 110.f},
	{12, "wave_preview", 3u, 2032.00003f, 9437.4587f, 217.90068f, 8613.1514f, 3628.1987f, 1648.6146f, 0.f},
	{14, "black_background", 3u, 4553.82826f, 7441.0425f, 986.18201f, 997.229f, 7135.2925f, 12887.627f, 0.f},
	{14, "gray_outline", 3u, 6082.8187f, 7441.0425f, 1096.182f, 1107.229f, 9973.2734f, 12667.627f, 0.f},
	{14, "frame_left", 3u, 3540.2017f, 9965.42945f, 57.409203f, 7794.9995f, 6965.585f, 4340.8599f, 0.f},
	{14, "outputs", 3u, 5811.7012f, 11440.3851f, 4588.1016f, 10720.973f, 2447.1992f, 1438.8242f, 0.f},
	{14, "outputs-3", 3u, 5815.6321f, 11434.9487f, 4631.5181f, 10765.182f, 2368.228f, 1339.5333f, 0.f},
	{14, "WYRM_FREQ_PARAM", 5u, 814.55664f, 8542.5576f, 0.f, 0.f, 0.f, 0.f, 260.f},
	{14, "WYRM_FINE_PARAM", 5u, 2225.269f, 8542.5576f, 0.f, 0.f, 0.f, 0.f, 220.f},
	{14, "WYRM_FM_ATTEN_PARAM", 5u, 5148.5684f, 8486.3018f, 0.f, 0.f, 0.f, 0.f, 220.f},
	{14, "WYRM_FOLD_PARAM", 5u, 6363.8403f, 8464.7998f, 0.f, 0.f, 0.f, 0.f, 220.f},
	{14, "WYRM_LOCK_BUTTON", 5u, 320.f, 7550.f, 0.f, 0.f, 0.f, 0.f, 160.f},
	{14, "WYRM_RESET_BUTTON", 5u, 755.f, 7550.f, 0.f, 0.f, 0.f, 0.f, 160.f},
	{14, "WYRM_WAVEFORM_SELECT", 5u, 1476.f, 7570.0098f, 0.f, 0.f, 0.f, 0.f, 160.f},
	{14, "WYRM_SLITHER_PARAM", 5u, 709.98511f, 11280.f, 0.f, 0.f, 0.f, 0.f, 220.f},
	{14, "WYRM_SLITHER_SPEED_PARAM", 5u, 2860.f, 11280.f, 0.f, 0.f, 0.f, 0.f, 220.f},
	{14, "WYRM_SLITHER_CV_INPUT", 5u, 1800.f, 11280.f, 0.f, 0.f, 0.f, 0.f, 190.f},
	{14, "WYRM_SLITHER_SPEED_CV_INPUT", 5u, 3950.0149f, 11280.f, 0.f, 0.f, 0.f, 0.f, 190.f},
	{14, "WYRM_VOCT_INPUT", 5u, 3565.9817f, 8548.0996f, 0.f, 0.f, 0.f, 0.f, 190.f},
	{14, "WYRM_FM_INPUT", 5u, 5145.6455f, 9795.4688f, 0.f, 0.f, 0.f, 0.f, 190.f},
	{14, "WYRM_SYNC_INPUT", 5u, 1800.f, 9954.583f, 0.f, 0.f, 0.f, 0.f, 190.f},
	{14, "WYRM_SYNC_MODE_PARAM", 5u, 2875.f, 9954.583f, 0.f, 0.f, 0.f, 0.f, 190.f},
	{14, "WYRM_LFO_MODE_PARAM", 5u, 3950.0149f, 9954.583f, 0.f, 0.f, 0.f, 0.f, 190.f},
	{14, "WYRM_FOLD_CV_INPUT", 5u, 6364.8999f, 9805.0596f, 0.f, 0.f, 0.f, 0.f, 190.f},
	{14, "WYRM_RAW_OUTPUT", 5u, 5145.6001f, 11260.f, 0.f, 0.f, 0.f, 0.f, 190.f},
	{14, "WYRM_OUT_OUTPUT", 5u, 6360.0532f, 11260.f, 0.f, 0.f, 0.f, 0.f, 190.f},
	{14, "WYRM_WAVE_EDITOR", 3u, 3553.85007f, 4168.85015f, 78.241165f, 1054.4412f, 6951.2178f, 6228.8179f, 0.f},
};

std::string normalizePath(std::string path) {
	std::replace(path.begin(), path.end(), '\\', '/');
	return path;
}

bool pathMatches(const std::string& requested, const char* atlasPath) {
	const std::string normalized = normalizePath(requested);
	const std::string atlas = normalizePath(atlasPath ? atlasPath : "");
	if (normalized == atlas) {
		return true;
	}
	if (normalized.size() <= atlas.size()) {
		return false;
	}
	const size_t offset = normalized.size() - atlas.size();
	return normalized[offset - 1u] == '/' && normalized.compare(offset, atlas.size(), atlas) == 0;
}

bool readFileBytes(const std::string& path, std::string* out) {
	if (!out) {
		return false;
	}
	std::ifstream file(path.c_str(), std::ios::binary);
	if (!file.good()) {
		return false;
	}
	std::ostringstream buffer;
	buffer << file.rdbuf();
	*out = buffer.str();
	return true;
}

uint64_t fnv1a64(const std::string& bytes) {
	uint64_t h = kFnv64Offset;
	for (unsigned char c : bytes) {
		h ^= uint64_t(c);
		h *= kFnv64Prime;
	}
	return h;
}

int findSvgIndex(const std::string& svgPath) {
	for (size_t i = 0; i < sizeof(kSvgAtlas) / sizeof(kSvgAtlas[0]); ++i) {
		if (pathMatches(svgPath, kSvgAtlas[i].path)) {
			return int(i);
		}
	}
	return -1;
}

bool atlasRecordIsCurrent(const std::string& svgPath, int svgIndex) {
	if (svgIndex < 0 || size_t(svgIndex) >= sizeof(kSvgAtlas) / sizeof(kSvgAtlas[0])) {
		return false;
	}
	static int8_t validation[sizeof(kSvgAtlas) / sizeof(kSvgAtlas[0])] = {};
	int8_t& cached = validation[size_t(svgIndex)];
	if (cached != 0) {
		return cached > 0;
	}

	std::string bytes;
	if (!readFileBytes(svgPath, &bytes)) {
		cached = -1;
		return false;
	}
	const SvgAtlasRecord& rec = kSvgAtlas[size_t(svgIndex)];
	const bool valid = bytes.size() == rec.size && fnv1a64(bytes) == rec.fnv64;
	cached = valid ? 1 : -1;
	return valid;
}

const std::vector<std::unordered_map<std::string, const AnchorAtlasRecord*>>& anchorIndexBySvg() {
	static std::vector<std::unordered_map<std::string, const AnchorAtlasRecord*>> index;
	if (!index.empty()) {
		return index;
	}
	index.resize(sizeof(kSvgAtlas) / sizeof(kSvgAtlas[0]));
	for (const AnchorAtlasRecord& rec : kAnchorAtlas) {
		const size_t svgIndex = size_t(rec.svgIndex);
		if (svgIndex >= index.size()) {
			continue;
		}
		index[svgIndex].emplace(rec.id ? rec.id : "", &rec);
	}
	return index;
}

} // namespace

bool lookupPanelAnchor(const std::string& svgPath, const std::string& elementId, PanelAnchorLookupResult* out) {
	if (!out) {
		return false;
	}
	*out = PanelAnchorLookupResult{};
	const int svgIndex = findSvgIndex(svgPath);
	if (svgIndex < 0 || !atlasRecordIsCurrent(svgPath, svgIndex)) {
		return false;
	}
	const auto& index = anchorIndexBySvg();
	const size_t indexPos = size_t(svgIndex);
	if (indexPos >= index.size()) {
		return false;
	}
	const auto& byId = index[indexPos];
	const auto found = byId.find(elementId);
	if (found == byId.end() || !found->second) {
		return false;
	}
	const AnchorAtlasRecord& rec = *found->second;
	out->found = true;
	out->hasCenter = (rec.flags & kAnchorHasCenter) != 0u;
	out->hasRect = (rec.flags & kAnchorHasRect) != 0u;
	out->hasRadius = (rec.flags & kAnchorHasRadius) != 0u;
	out->cx = rec.cx;
	out->cy = rec.cy;
	out->x = rec.x;
	out->y = rec.y;
	out->width = rec.width;
	out->height = rec.height;
	out->radius = rec.radius;
	return true;
}

PanelAnchorAtlasStatus getPanelAnchorAtlasStatus(const std::string& svgPath) {
	const int svgIndex = findSvgIndex(svgPath);
	if (svgIndex < 0) {
		return PanelAnchorAtlasStatus::Missing;
	}
	return atlasRecordIsCurrent(svgPath, svgIndex)
		? PanelAnchorAtlasStatus::Valid
		: PanelAnchorAtlasStatus::StaleOrUnreadable;
}

} // namespace panel_svg
